/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Gradle plugin project to get you started.
 * For more details on writing Custom Plugins, please refer to https://docs.gradle.org/9.5.0/userguide/custom_plugins.html in the Gradle documentation.
 */

plugins {
    `kotlin-dsl`
}

group = "io.fegzdev"

gradlePlugin {
    website = "https://github.com/fegzdev/kmp-splash-screen"
    vcsUrl = "https://github.com/fegzdev/kmp-splash-screen.git"

    plugins {
        create("kmp-splash-screen") {
            id = "io.fegzdev.kmp-splash-screen"
            displayName = "KMP Splash Screen"
            description = "Generate native splash screen resources from a unified Kotlin DSL"
            tags = listOf(
                "kotlin",
                "multiplatform",
                "kmp",
                "compose",
                "cmp",
                "splash",
                "screen",
                "android",
                "ios",
                "desktop",
                "web"
            )
            implementationClass = "io.fegzdev.kmp_splash_screen.KmpSplashScreenPlugin"
        }
    }
}
